views/forms.py
from flask import Blueprint, render_template, redirect, url_for, request

forms_bp = Blueprint('forms', __name__ , url_prefix='/forms')

@forms_bp.route('/', methods=['POST'])
def forms():
    people = request.form.get('people')
    dat_from_year = request.form.get('dat_from_year')
    dat_to_year = request.form.get('dat_to_year')
    locations = request.form.get('locations')
    let_con = request.form.get('let_con')

    # Construct the query parameters
    query_params = {}
    if people and people != "all people":
        query_params['people'] = people
    if dat_from_year and dat_from_year != "all years":
        query_params['dat_from_year'] = dat_from_year
    if dat_to_year and dat_from_year != "all years":
        query_params['dat_to_year'] = dat_to_year
    if locations and locations != "all places":
        query_params['locations'] = locations
    if let_con and let_con != "all content":
        query_params['let_con'] = let_con

    # Redirect to the new URL with query parameters
    return redirect(url_for('forms.results', **query_params))

@forms_bp.route('/advance')
def results():
    return render_template('results.jinja2', title="Results")

__init__.py
from flask import Flask
from views.home import home_bp, browse_bp

def create_app():
    app = Flask(__name__)
    app.config.from_object('app.config.Config')

    app.register_blueprint(home_bp)
    app.register_blueprint(browse_bp)

    return app

views/about.py
from flask import Blueprint, render_template

about_bp = Blueprint('about', __name__)

@about_bp.route('/about')
def about():
    return render_template('about.jinja2', title="About")

views/advance.py
from flask import Blueprint, render_template, request

advance_bp = Blueprint('advance', __name__)

@advance_bp.route('/advance')
def advance():
    people = request.args.get('people')
    locations = request.args.get('locations')
    dat_from_year = request.args.get('dat_from_year' , 'all years')
    dat_to_year = request.args.get('dat_to_year' , 'all years')
    let_con = request.args.get('let_con')

    start_year = 1500
    end_year = 1841
    months_map = {
        "January": "01",
        "February": "02",  
        "March": "03",
        "April": "04",
        "May": "05",
        "June": "06",
        "July": "07",
        "August": "08",
        "September": "09",
        "October": "10",
        "November": "11",
        "December": "12"
    }

    # Variables used inside advance/letter.jinja2
    languages = [
        "Ancient Greek",
        "Basque",
        "Cornish",
        "Czech",
        "Danish",
        "Dutch",
        "English",
        "French",
        "German",
        "Hebrew",
        "Irish",
        "Italian",
        "Latin",
        "Old French",
        "Polish",
        "Scottish Gaelic",
        "Spanish",
        "Swedish",
        "Welsh"
    ]

    document_types = [
        "Digital copy",
        "Draft",
        "Extract",
        "Letter",
        "Manuscript copy",
        "Printed copy",
        "Other"
    ]

    return render_template('advance.jinja2', title="Search +", 
                           people=people, 
                           locations=locations, 
                           dat_from_year=dat_from_year, 
                           dat_to_year=dat_to_year,
                           let_con=let_con,
                           months_map=months_map,
                           start_year=start_year,
                           end_year=end_year,
                           languages=languages,
                           document_types=document_types)

views/browse.py
from flask import Blueprint, render_template, redirect, url_for, request

browse_bp = Blueprint('browse', __name__ , url_prefix='/browse')

@browse_bp.route('/')
def browse():
    return redirect(url_for('browse.people'))

@browse_bp.route('/people')
def people():
    letter = request.args.get('letter', '').lower()
    return render_template('/pages/browse/people.jinja2', title="Browse:People" , letter=letter)

@browse_bp.route('/locations')
def locations():
    letter = request.args.get('letter', '').lower()
    return render_template('/pages/browse/locations.jinja2', title="Browse:Locations" , letter=letter)

@browse_bp.route('/organisations')
def organisations():
    letter = request.args.get('letter', '').lower()
    return render_template('/pages/browse/organisations.jinja2', title="Browse:Organisations", letter=letter)

@browse_bp.route('/institutions')
def institutions():
    return render_template('/pages/browse/institutions.jinja2', title="Browse:Institutions")

@browse_bp.route('/works')
def works():
    current_year = request.args.get('year', default=1600, type=int)
    current_decade = (current_year // 10) * 10

    years_range = range(current_decade, current_decade + 10)
    
    return render_template('/pages/browse/works.jinja2', title="Browse:Works" ,current_year=current_year, current_decade=current_decade, years_range=years_range)

views/collections.py
from flask import Blueprint, render_template

collections_bp = Blueprint('collections', __name__)

@collections_bp.route('/collections')
def collections():
    return render_template('collections.jinja2', title="Collections")

views/contribute.py
from flask import Blueprint, render_template

contribute_bp = Blueprint('contribute', __name__)

@contribute_bp.route('/contribute')
def contribute():
    return render_template('contribute.jinja2', title="Contribute")

views/errors.py
from flask import Blueprint, render_template

errors_bp = Blueprint('errors', __name__)

@errors_bp.app_errorhandler(404)
def route_not_found(err):
    return render_template('page_not_found.jinja2', title="Page not found"), 404

@errors_bp.app_errorhandler(500)
def internal_server_error(err):
    return render_template('internal_server_error.jinja2', err=str(err), title="Internal error"), 500

views/home.py
from flask import Blueprint, render_template

home_bp = Blueprint('home', __name__)

@home_bp.route('/')
def home():
    return render_template('home.jinja2', title="Home")


# @home_bp.route('/forms', methods=['POST'])
# def home_search():
#     # Extracting form data
#     people = request.form.get('people')
#     dat_from_year = request.form.get('dat_from_year')
#     dat_to_year = request.form.get('dat_to_year')
#     locations = request.form.get('locations')
#     let_con = request.form.get('let_con')

    
#     # Construct the query parameters
#     query_params = {}
#     if people:
#         query_params['people'] = people
#     if dat_from_year:
#         query_params['dat_from_year'] = dat_from_year
#     if dat_to_year:
#         query_params['dat_to_year'] = dat_to_year
#     if locations:
#         query_params['locations'] = locations
#     if let_con:
#         query_params['let_con'] = dat_from_year
    
#     # Redirect to the new URL with query parameters
#     return redirect(url_for('forms.results', **query_params))

templates/_edges_common_js.jinja2
{# Loading base files for edges #}
<script type="text/javascript" src="../static/libs/edges/vendor/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script type="text/javascript" src="../static/libs/edges/src/edges.js"></script>
    
{# Loading datasource files for edges #}
<script type="text/javascript" src="../static/libs/edges/src/datasources/solr9x.js"></script>

{# Loading edges components #}
<script type="text/javascript" src="../static/libs/edges/src/components/RefiningANDTermSelector.js"></script>
<script type="text/javascript" src="../static/libs/edges/src/components/ResultsDisplay.js"></script>
<script type="text/javascript" src="../static/libs/edges/src/components/FullSearchController.js"></script>
<script type="text/javascript" src="../static/libs/edges/src/components/Pager.js"></script>
{# Loading edges default template #}
<script type="text/javascript" src="../static/libs/edges/src/templates/bs3/Facetview.js"></script>

{# Loading edges renderer #}
<script type="text/javascript" src="../static/libs/edges/src/renderers/bs3/RefiningANDTermSelector.js"></script>
<script type="text/javascript" src="../static/libs/edges/src/renderers/bs3/ResultsFieldsByRow.js"></script>
<script type="text/javascript" src="../static/libs/edges/src/renderers/bs3/FullSearchController.js"></script>
<script type="text/javascript" src="../static/libs/edges/src/renderers/bs3/Pager.js"></script>
<script type="text/javascript" src="../static/libs/edges/src/renderers/bs5/SearchBox.js"></script>

templates/about.jinja2
{% extends "base.jinja2" %}

{% block title %}About{% endblock %}

{% block content %}
    <div>
        <div class="fixed-nav">
            <a href="#context">Context</a>
            <a href="#citation">Citation Guidelines</a>
            <a href="#copyright">Copyright and Scholarly Responsibility</a>
            <a href="#issues">Known Issues</a>
            <a href="#credits">Credits</a>
            <a href="#technical">Technical Overview</a>
            <a href="#cookies">Cookies</a>
            <a href="#contact">Contact</a>
        </div> 

        <div class="row">

            <div class="large-2 columns"><!-- dummy column -->&nbsp;</div>

            <div class="large-10 columns" style="padding-left:25px">

                <div id="about">
                    <br/>
                    <h1>About</h1>

                    <p>
                        <i>Early Modern Letters Online</i>is a combined finding aid and editorial interface for basic descriptions of 
                        early modern correspondence: a collaboratively populated union catalogue of sixteenth-, seventeenth-, and 
                        eighteenth-century letters. <strong>EMLO is an active project in continual development:</strong> 
                        please let us know what you think, and get involved!
                    </p>
                </div>

                <div id="context" class="large-10 columns" style="padding-left:25px">
                    {% include './components/about/context.jinja2' %}
                </div>
                
                <div id="citation" class="large-10 columns" style="padding-left:25px">
                    {% include './components/about/citation.jinja2' %}
                </div>

                <div id="copyright" class="large-10 columns" style="padding-left:25px">
                    {% include './components/about/copyright.jinja2' %}
                </div>

                <div id="issues" class="large-10 columns" style="padding-left:25px">
                    {% include './components/about/issues.jinja2' %}
                </div>

                <div id="credits" class="large-10 columns" style="padding-left:25px">
                    {% include './components/about/credits.jinja2' %}
                </div>

                <div id="technical" class="large-10 columns" style="padding-left:25px">
                    {% include './components/about/technical.jinja2' %}
                </div>

                <div id="cookies" class="large-10 columns" style="padding-left:25px">
                    {% include './components/about/cookies.jinja2' %}
                </div>

                <div id="contact" class="large-10" style="padding-left:25px">
                    {% include './components/about/contact.jinja2' %}
                </div>
            </div>  
        </div>
    </div>    
{% endblock %}


{% block extra_js_bottom %}
   
{% endblock extra_js_bottom %}

templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Arvo" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">
    <title>Early Modern Letter Online : {{ title }}</title>
    {% block extra_stylesheets %}{% endblock %}
    <script>
        function quickSearch(event) {
            event.preventDefault();

            try {
                const searchQuery = document.getElementById("all_search").value

                window.location.href = `${window.location.origin}/forms/advance?everything=${searchQuery}&search_type=quick`
            } catch(err) {
                console.error(err)
            } 
        }
    </script>
</head>
<body>
    <!-- START header / menu -->
    <div class="contain-to-grid yellow-bg">
        <nav class="top-bar yellow-bg" data-topbar>
            <ul class="title-area">
                <li class="name">
                    <h1>
                        <a style="min-width:152px" class="no-decoration" href="/" accesskey="1">
                            <img style="width:152px;"
                                src="{{ url_for('static', filename='img/emlo_logo.png') }}"
                                alt="EMLO logo"
                                class="show-for-large-up menu-name"/>
                        </a>
                        <strong>
                            <a class="no-decoration hide-for-large-up" href="/" accesskey="1">EMLO &nbsp;&nbsp;</a>
                        </strong>
                    </h1>
                </li>
                <li class="toggle-topbar menu-icon">
                    <a href="/">Menu</a>
                </li>
            </ul>

            <section class="top-bar-section yellow-bg">
                <!-- Left Nav Section -->
                <ul class="left yellow-bg">
                    <li><a href="{{ url_for('home.home') }}">Home</a></li>
                    <li><a href="{{ url_for('advance.advance') }}">Search+</a></li>
                    <li><a href="{{ url_for('browse.browse') }}">Browse</a></li>
                    <li><a href="http://emlo-portal.bodleian.ox.ac.uk/collections/?page_id=480">Collections</a></li>
                    <li><a href="{{ url_for('contribute.contribute') }}">Contribute</a></li>
                    <li><a href="{{ url_for('about.about') }}">About</a></li>
                </ul>

                <!-- Right Nav Section -->
                <ul class="right yellow-bg">
                    <!-- search bar -->
                    <li class="has-form">
                        <form onSubmit="quickSearch(event)" id="circle-search">
                            <div class="row">
                                <input style="position: static; margin-top: 7px" id="all_search" type="search" placeholder="Keywords..."/>
                            </div>
                        </form>
                    </li>
                    <!-- end of search bar -->
                </ul>

            </section>
        </nav>
    </div>
    <!-- END header / menu -->

    <!-- START content -->
    {% block content %}{% endblock %}
    <!-- END content -->

    <!-- START footer -->
    <div class="footer-divider">
        <div class="row footer">
            <div class="large-3 medium-6 columns centered">
                <a href="http://www.culturesofknowledge.org/" target="_blank">
                    <img src="{{ url_for('static', filename='img/CofKLogoBlack.png') }}"
                        alt="Cultures of Knowledge Logo"
                        class="hide-for-small"/>
                    <span class="hide-for-medium-up">Cultures of Knowledge</span>
                </a>
            </div>

            <div class="large-3  medium-6 columns centered">
                <a href="http://www.bodleian.ox.ac.uk/" target="_blank">
                    <img src="{{ url_for('static', filename='img/Bodleian_Libraries_logo.svg') }}"
                        alt="Bodleian Libraries Logo" width="120"
                        class="hide-for-small"
                        style="margin-left:40px;"/>
                    <span class="hide-for-medium-up">Bodleian Libraries</span>
                </a>
            </div>

            <div class="large-3 medium-6 columns centered">
                <a href="http://www.mellon.org/" target="_blank">
                    <img src="{{ url_for('static', filename='img/Andrew_Mellon_Foundation_logo.svg') }}"
                        alt="Andrew Mellon Foundation Logo" width="140"
                        class="hide-for-small"/>
                    <span class="hide-for-medium-up">Andrew Mellon Foundation</span>
                </a>
            </div>

            <div class="large-3 medium-6 columns centered">
                <a href="http://ox.ac.uk" target="_blank">
                    <img src="{{ url_for('static', filename='img/University_of_Oxford_logo.gif') }}"
                        alt="University of Oxford Logo"
                        class="hide-for-small"/>
                    <span class="hide-for-medium-up">University of Oxford</span>
                </a>
            </div>

        </div>
    </div>
    <!-- END footer -->

    {% block extra_js_bottom %}{% endblock %}
</body>
</html>

templates/base/browse_base.jinja2
{% extends "base.jinja2" %}

{% block title %}Browse{% endblock %}

{% block extra_stylesheets %}
<style>
ul.alphabet li, ul.numbers li {
    background-color: #ddd;
    margin-left: 4px;
}
.pagination-centered ul.pagination li {
    margin-bottom: 5px;
}

ul.pagination li a {
    color:black;
}
</style>
{% endblock %}

{% block content %}

    <br><br>
    <div class="panel">
        <div class="row">
            {# Space #}
            <div class="columns hide-for-small hide-for-medium large-2">
            </div>

            <div class="columns small-12 large-10 browseby">
                <ul class="small-block-grid-3 medium-block-grid-6 large-block-grid-6">
                    <li><h3>Browse by</h3></li>

                    <li class="stats-text text-center {% if request.endpoint == 'browse.people' %}active{% endif %}">
                        <a href="{{ url_for('browse.people') }}">
                            <img src="{{ url_for('static', filename='img/icon-stats-people.png') }}" alt="People icon" class="stats-icon"><br>People
                        </a>
                    </li>

                    <li class="stats-text text-center {% if request.endpoint == 'browse.locations' %}active{% endif %}">
                        <a href="{{ url_for('browse.locations') }}">
                            <img src="{{ url_for('static', filename='img/icon-stats-locations.png') }}" alt="Locations icon" class="stats-icon"><br>Locations
                        </a>
                    </li>

                    <li class="stats-text text-center {% if request.endpoint == 'browse.organisations' %}active{% endif %}">
                        <a href="{{ url_for('browse.organisations') }}">
                            <img src="{{ url_for('static', filename='img/icon-stats-organisations.png') }}" alt="Organizations icon" class="stats-icon"><br>Organizations
                        </a>
                    </li>

                    <li class="stats-text text-center {% if request.endpoint == 'browse.institutions' %}active{% endif %}">
                        <a href="{{ url_for('browse.institutions') }}">
                            <img src="{{ url_for('static', filename='img/icon-stats-repositories.png') }}" alt="Repositories icon" class="stats-icon"><br>Repositories
                        </a>
                    </li>

                    <li class="stats-text text-center {% if request.endpoint == 'browse.works' %}active{% endif %}">
                        <a href="{{ url_for('browse.works') }}">
                            <img src="{{ url_for('static', filename='img/icon-stats-calendar.png') }}" alt="Years icon" class="stats-icon"><br>Years
                        </a>
                    </li>
                </ul>
            </div>
        </div>
	</div>

    <div id="browse-content" class="row">
        {% block browse_content %}{% endblock %}
    </div>

{% endblock %}


{% block extra_js_bottom %}
{% endblock extra_js_bottom %}

templates/components/home/search.jinja2
<div class="panel" style="">
  <div class="row">
    <form id="search" action="/forms/" method="post">

      {# Search people - Starts #}
      <div class="large-11 small-10 columns">
        <label for="people">Search people</label>
        <input
          id="people"
          name="people"
          type="text"
          class="text"
          placeholder="all people"
          value=""
          title="Search letters for authors, senders, recipients, and people mentioned, e.g. 'Samuel Hartlib', 'John Aubrey', or 'The Royal Society'. &lt;
                  br/&gt;&lt;br/&gt;Search is not case sensitive."
        />
      </div>
      <div class="large-1 small-2 columns">
        <label>&nbsp;<!-- for alingment--></label>
        <span
          data-tooltip=""
          aria-haspopup="true"
          class="has-tip tip-top"
          data-selector="tooltip-lz7zrq1x0"
          aria-describedby="tooltip-lz7zrq1x0"
          title=""
        >
          <img
            style="min-width: 25px; text-align: left"
            class="help"
            src="/static/img/icon-help.png"
            alt="Help"
          />
        </span>
      </div>
      {# Search people - Ends #}

      {# Search year - Starts #}
      <div class="large-6 small-5 columns">
        <label>Search from year</label>
        <select
          id="dat_from_year"
          name="dat_from_year"
          title="Search from this year."
          class="year_from"
          onchange="changeEventOnFrom(this.options[this.selectedIndex].value)"
        >
          <option class="default" selected="selected">all years</option>
          {% for year in range(1500, 1841) %}
          <option value="{{ year }}">{{ year }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="small-5 columns">
        <label>Search to year</label>
        <select
          id="dat_to_year"
          name="dat_to_year"
          title="Search up to this year."
          class="year_to"
          onchange="changeEventOnTo(this.options[this.selectedIndex].value)"
        >
          <option class="default" selected="selected">all years</option>
          {% for year in range(1500, 1841) %}
          <option value="{{ year }}">{{ year }}</option>
          {% endfor %}
        </select>
      </div>

      <div class="large-1 small-2 columns">
        <label>&nbsp;<!-- for alignment--></label>
        <span
          data-tooltip=""
          aria-haspopup="true"
          class="has-tip tip-top"
          data-selector="tooltip-lz7zrq1x1"
          aria-describedby="tooltip-lz7zrq1x1"
          title=""
        >
          <img
            style="min-width: 25px; text-align: left"
            class="help"
            src="/static/img/icon-help.png"
            alt="Help"
          />
        </span>
      </div>
      {# Search year - Ends #}

      {# Search places - Starts #}
      <div class="large-11 small-10 columns">
        <label for="locations">Search places</label>

        <input
          id="locations"
          name="locations"
          type="text"
          class="text"
          placeholder="all places"
          value=""
          onfocus="
  javascript:textClear(this);"
          onblur="
  javascript:textFill(this);"
          title="Search the places that letters were sent from or to, e.g. 'Queen's College', 'Paris', or 'Spain'. &lt;br/&gt;&lt;br/&gt;Search is not case sensitive."
        />
      </div>
      <div class="large-1 small-2 columns">
        <label>&nbsp;<!-- for alingment--></label>

        <span
          data-tooltip=""
          aria-haspopup="true"
          class="has-tip tip-top"
          data-selector="tooltip-lz7zrq1x2"
          aria-describedby="tooltip-lz7zrq1x2"
          title=""
        >
          <img
            style="min-width: 25px; text-align: left"
            class="help"
            src="/static/img/icon-help.png"
            alt="Help"
          />
        </span>
      </div>
      {# Search places - Ends #}

      {# Search content - Starts #}
      <div class="large-11 small-10 columns">
        <label>Search content</label>

        <input
          id="let_con"
          name="let_con"
          type="text"
          class="text"
          placeholder="all content"
          value=""
          onfocus="
  javascript:textClear(this);"
          onblur="
  javascript:textFill(this);"
          title="Search across abstracts, keywords, incipits, excipits, transcriptions, and enclosures, e.g. 'Spider' or 'Mathematics'. &lt;br/&gt;&lt;br/&gt;Search is not case sensitive. "
        />
      </div>
      <div class="large-1 small-2 columns">
        <label>&nbsp;<!-- for alingment--></label>

        <span
          data-tooltip=""
          aria-haspopup="true"
          class="has-tip tip-top"
          data-selector="tooltip-lz7zrq1x3"
          aria-describedby="tooltip-lz7zrq1x3"
          title=""
        >
          <img
            style="min-width: 25px; text-align: left"
            class="help"
            src="/static/img/icon-help.png"
            alt="Help"
          />
        </span>
      </div>

      <div class="large-3 columns">
        <input
          class="button submit search-related"
          type="submit"
          name="submit-normal"
          value="Search"
          style="margin-top: 13px"
        />

        <input
          type="hidden"
          id="search_type"
          name="search_type"
          value="normal"
        />
      </div>
      {# Search content - Ends #}
    </form>

    <div class="large-9 hide-for-small columns" style="margin-top: 10px">
      <p class="text-center" style="margin-bottom: 0">
        Want a full set of fields? Try
        <a href="{{ url_for('advance.advance') }}">Search+</a>
      </p>
      <p class="text-center" style="">
        Prefer things at a glance? You can also
        <a href="{{ url_for('browse.people') }}">Browse</a>
      </p>
    </div>
    <div class="small-12 show-for-small columns" style="margin-top: 0">
      <p class="text-center" style="margin-bottom: 0">
        Want a full set of fields? Try
        <a href="{{ url_for('advance.advance') }}">Search+</a>
      </p>
      <p class="text-center" style="">
        Prefer things at a glance? You can also
        <a href="{{ url_for('browse.people') }}">Browse</a>
      </p>
    </div>
  </div>
</div>

templates/components/home/stats.jinja2
{# TODO: The values have to be dynamic in nature #}
<div class="row">
      <div class="large-12 columns">
        <ul class="small-block-grid-2 medium-block-grid-5 large-block-grid-10">
          <li class="stats-text text-center">
            <img
              src="/static/img/icon-stats-people.png"
              alt="People icon"
              class="stats-icon"
            /><br />
            36262<br />
            <a href="{{ url_for('browse.people') }}"> People</a>
          </li>

          <li class="stats-text text-center">
            <img
              src="/static/img/icon-stats-locations.png"
              alt="Locations icon"
              class="stats-icon"
            /><br />
            7610<br />
            <a href="{{ url_for('browse.locations') }}">
              Locations</a
            >
          </li>

          <li class="stats-text text-center">
            <img
              src="/static/img/icon-stats-organisations.png"
              alt="Organisations icon"
              class="stats-icon"
            /><br />
            1435<br />
            <a href="{{ url_for('browse.organisations') }}">
              Organisations</a
            >
          </li>

          <li class="stats-text text-center">
            <img
              src="/static/img/icon-stats-repositories.png"
              alt="Repositories icon"
              class="stats-icon"
            /><br />
            593<br />
            <a href="{{ url_for('browse.institutions') }}">
              Repositories</a
            >
          </li>

          <li class="stats-text text-center">
            <img
              src="/static/img/icon-stats-Catalogues.png"
              alt="Catalogues icon"
              class="stats-icon"
            /><br />
            223<br />
            <a
              href="{{ url_for('collections.collections') }}"
            >
              Catalogues</a
            >
          </li>

          <li class="stats-text text-center">
            <img
              src="/static/img/icon-stats-works.png"
              alt="Letters icon"
              class="stats-icon"
            /><br />
            214014<br />
            Letters
          </li>

          <li class="stats-text text-center">
            <img
              src="/static/img/icon-stats-manifestations.png"
              alt="Versions icon"
              class="stats-icon"
            /><br />
            269495<br />
            Versions
          </li>

          <li class="stats-text text-center">
            <img
              src="/static/img/icon-stats-images.png"
              alt="Images icon"
              class="stats-icon"
            /><br />
            11242<br />
            Images
          </li>

          <li class="stats-text text-center">
            <img
              src="/static/img/icon-stats-comments.png"
              alt="Comments icon"
              class="stats-icon"
            /><br />
            87715<br />
            Comments
          </li>

          <li class="stats-text text-center">
            <img
              src="/static/img/icon-stats-related%20resources.png"
              alt="Resources icon"
              class="stats-icon"
            /><br />
            220192<br />
            Resources
          </li>
        </ul>
        <!-- end block grid -->
      </div>
      <!-- div column -->
    </div>

templates/internal_server_error.jinja2
{% extends "base.jinja2" %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="row">

        <div class="large-2 columns"><!-- dummy column -->&nbsp;</div>

        <div class="large-10 columns" style="padding-left:25px">
            <br/>
            <h2>Internal Server Error</h2>
            <p>Sorry, something went wrong on our end. Please try again later.</p>

            <p id="hiddenError" style="display:none;">{{ err }}</p>

            <div class=row>
                {% if err %}
                    <a style="margin:0px 20px" onclick="copyToClipboard()">Copy Error Details</a>
                {% endif %}
                <a href="{{ url_for('home.home') }}">Go to Home</a>
            </div>
            <br/><br/><br/>
        </div>
    </div>
{% endblock %}


{% block extra_js_bottom %}
<script>
function copyToClipboard() {
    console.log("jie")
    const errorText = document.getElementById('hiddenError').innerText;
    navigator.clipboard.writeText(errorText).then(function() {
        alert('Error details copied to clipboard!');
    }, function(err) {
        alert('Failed to copy error details.');
    });
}
</script>
{% endblock extra_js_bottom %}

templates/page_not_found.jinja2
{% extends "base.jinja2" %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="row">

        <div class="large-2 columns"><!-- dummy column -->&nbsp;</div>

        <div class="large-10 columns" style="padding-left:25px">
            <br/>
            <h2>Missing</h2>
            <p>Sorry, that record has not been found, it may have been merged with another record. Sorry about that.</p>
            <a href="{{ url_for('home.home') }}">Go to Home</a>
            <br/><br/><br/>
        </div>
    </div>
{% endblock %}


{% block extra_js_bottom %}
{% endblock extra_js_bottom %}

templates/pages/browse/location.jinja2
{% extends "/base/browse_base.jinja2" %}

{% block browse_content %}
    <div>
        <h1>I am Location</h1>
    </div>
{% endblock %}